name: JF Test Site
favicon: null
layout_spectrum: 0.33811
typography_spectrum: 0.34732
title: Just testing out The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
