title: Just testing out The Grid
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2914894
  brandStrength: 0.8808511
  lightness: 0.04468085
  brandColors:
    - '#FFFFFF'
    - '#13171A'
    - '#76716B'
    - '#6B98D1'
    - '#CEC7BD'
  rhythmicContrast: 0.3319149
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: JF Test Site
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6978723
layout_spectrum: 0.2531915
