name: JF Test Site
favicon: null
layout_spectrum: 0.3207777424249798
typography_spectrum: 0.5131646157242358
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9355973566416651
  lightness: 0.22759044519625604
  saturation: 0.9186277796979994
  rhythmicContrast: 0.0958498022519052
purpose: []
